image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-redirect-from
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master