build:
  stage: build
  image: ruby:2.3
  script:
    - gem install jekyll jekyll-sitemap
    - jekyll build -d public
  artifacts:
    paths:
      - public

publish:
  stage: deploy
  image: alpine
  environment: 
    name: production
  dependencies:
    - build
  script:
    - apk update
    - apk add ca-certificates
    - apk add lftp
    - lftp -c "set ssl:verify-certificate on && set ftp:ssl-force on && open -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER && mirror -vvv -R -e --scan-all-first --transfer-all --overwrite --parallel=24 ./public $FTP_LOCATION"
  only:
    - master