name: Jiří {x2} Činčura
description: Taking something that can't be done, and then doing it.
url: http://blog.cincura.net
#url: http://cincuranet.github.io/blog-cincura-net
permalink: /:title
paginate: 20
paginate_path: page-:num