name: Jiří /{x2}\ Činčura
description: Taking something that /can't\ be done, and then /doing it\.
url: http://blog.cincura.net
#url: file:///C:/Users/Jiri/Documents/www/cincura.net/blog/src/_site
permalink: /:title/
timezone: Etc/UTC
excerpt_separator: <!-- excerpt -->
site_posts: 20
feed_posts: 20
feed: atom.xml
disqus_base_url: http://blog.cincura.net