name: Jiří /{x2}\ Činčura
description: Taking something that /can't\ be done, and then /doing it\.
url: http://blog.cincura.net
#url: file:///C:/Users/Jiri/Documents/www/blog.cincura.net/blog/src/_site
permalink: /:title/
timezone: UTC
excerpt_separator: <!-- excerpt -->
site_posts: 20
feed_posts: 20
feed: atom.xml
sitemap: sitemap.xml
disqus_shortname: blogcincuranet
disqus_base_url: http://blog.cincura.net
markdown: redcarpet
redcarpet:
  extensions:
    - smart
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
