heading1: "tabs ↹ over ␣ ␣ ␣ spaces"
heading1_accent: "over"
heading2: "Jiří {x2} Činčura"
heading2_accent: "{x2}"
address: "www.tabsoverspaces.com"
iaddress: "i.tabsoverspaces.com"
excerpt_separator: "<!-- excerpt -->"
site_posts: 60
feed_posts: 60
feed: feed.xml
sitemap: sitemap.xml