name: Jiří <span class="accent">{x2}</span> Činčura
description: Taking something that <span class="accent">can't</span> be done, and then <span class="accent">doing it</span>.
permalink: /:title/
timezone: UTC
protocol: "https:"
address: //blog.cincura.net
excerpt_separator: <!-- excerpt -->
excerpt_link_name: Continue reading...
site_posts: 20
feed_posts: 20
feed: feed.xml
sitemap: sitemap.xml
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
gems: [jekyll-sitemap]