name: Jiří {x2} Činčura
description: Taking something that can't be done, and then doing it.
permalink: /:title/
timezone: UTC
address: //blog.cincura.net
excerpt_separator: <!-- excerpt -->
excerpt_link_name: Continue reading...
site_posts: 20
feed_posts: 20
feed: feed.xml
sitemap: sitemap.xml
gems: [jekyll-sitemap, jekyll-redirect-from]