name: Jiří {x2} Činčura
description: Taking something that <span class="low">can't</span> be done, and then <span class="low">doing it</span>.
permalink: /:title/
timezone: UTC
protocol: "https:"
address: //blog.cincura.net
excerpt_separator: <!-- excerpt -->
excerpt_link_name: Continue reading...
site_posts: 20
feed_posts: 20
feed: feed.xml
sitemap: sitemap.xml
gems: [jekyll-sitemap, jekyll-redirect-from]